Categories = {
    "label-10": [
        "Nucleus",
        "Cytoplasm",
        "Extracellular",
        "Mitochondrion",
        "Cell.membrane",
        "Endoplasmic.reticulum",
        "Plastid",
        "Golgi.apparatus",
        "Lysosome/Vacuole",
        "Peroxisome",
    ],
    "label-91": [
        "Nucleus",
        "Chromosome",
        "Centromere",
        "Chromatin",
        "Telomere",
        "Nuclear body",
        "PML body",
        "Nuclear pore complex",
        "Nuclear speckle",
        "Nucleolus",
        "Nucleolar fibrillar center",
        "Nucleolus rim",
        "Nucleoplasm",
        "Nucleus membrane",
        "Nucleus inner membrane",
        "Centrosome",
        "Centriolar satellite",
        "Centriole",
        "Cytoplasm",
        "Cytoplasmic granule",
        "Cytoplasmic ribonucleoprotein granule",
        "P-body",
        "Stress granule",
        "Cytoplasmic vesicle",
        "Autophagic vesicle",
        "Autophagosome",
        "Endocytic vesicle",
        "Clathrin-coated vesicle",
        "Phagosome",
        "Secretory vesicle",
        "Acrosome",
        "Synaptic vesicle",
        "Cytoskeleton",
        "Phragmoplast",
        "Spindle",
        "Spindle pole",
        "Cytosol",
        "Myofibril",
        "Sarcomere",
        "Z line",
        "Spindle pole body",
        "Cell wall",
        "Secreted",
        "Mitochondrion",
        "Mitochondrion intermembrane space",
        "Mitochondrion matrix",
        "Mitochondrion membrane",
        "Mitochondrion inner membrane",
        "Mitochondrion outer membrane",
        "Cell junction",
        "Adherens junction",
        "Focal adhesion",
        "Tight junction",
        "Cell membrane",
        "Membrane raft",
        "Endoplasmic reticulum",
        "Endoplasmic reticulum lumen",
        "Endoplasmic reticulum membrane",
        "Endoplasmic reticulum-golgi intermediate compartment",
        "Chloroplast",
        "Chloroplast membrane",
        "Chloroplast stroma",
        "Chloroplast thylakoid",
        "Chloroplast thylakoid membrane",
        "Golgi apparatus",
        "Cis-golgi network",
        "Golgi stack",
        "Trans-golgi network",
        "Lysosome",
        "Lysosome membrane",
        "Vacuole",
        "Vacuole membrane",
        "Vesicle",
        "Peroxisome",
        "Peroxisome membrane",
        "Cell projection",
        "Axon",
        "Growth cone",
        "Cilium",
        "Dendrite",
        "Dendritic spine",
        "Flagellum",
        "Pseudopodium",
        "Lamellipodium",
        "Ruffle",
        "Endosome",
        "Endosome membrane",
        "Lipid droplet",
        "Melanosome",
        "Midbody",
        "Spore",
    ],
}

